# Generated by Django 2.2.4 on 2020-12-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktioneryapp', '0006_auto_20201223_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(max_length=255),
        ),
    ]
