# Generated by Django 2.2.4 on 2020-12-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktioneryapp', '0008_auto_20201223_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='booktioneryapp.Order'),
        ),
    ]
