# Generated by Django 2.2.4 on 2020-12-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktioneryapp', '0011_auto_20201226_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='deleted',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
    ]
