# Generated by Django 2.2.4 on 2020-12-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktioneryapp', '0012_cart_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
