from django.urls import path
from . import views

urlpatterns = [
    path('',views.welcome, name='search'),
    path('success',views.success ),
    path('search',views.search),
    path('register',views.reg ),
    path('register2',views.registration ),
    path('details/<product_cat_name>/<int:product_id>',views.view_product ),
    path('login',views.login),
    path('logout',views.logout),
    path('<int:id>',views.user_profile ),
    path('addcart/<product_cat_name>/<int:productid>',views.addcart),
    path('cart/<int:userid>',views.viewcart, name='login'),
    path('deleteitem/<int:item_id>/<int:user_id>',views.delete_from_cart ),
    path('products/<category_name>',views.category_products ),
    path('success/products/<category_name>',views.success_category_products ),
    path('addcart2/<int:product_id>',views.addcart2 ),
    path('order/<int:userid>',views.order ),
    path('admin',views.adminlogin),
    path('adminlogin',views.admin),
    path('admindashboard/orders',views.dashboard),
    path('admindashboard/users',views.dashboard_users),
    path('admindashboard/products',views.dashboard_products),
    path('delete/<int:product_id>',views.delete_product),
    path('update/<int:product_id>',views.update_product),
    path('update_product/<int:product_id>',views.update_product2),
    path('add_product/',views.add_product),
    path('add_product2',views.add_product2),
]
